package modelo;
// Generated 21/05/2019 04:22:37 PM by Hibernate Tools 4.3.1



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int idcomentario;
     private Marcador marcador;
     private Usuario usuario;
     private String comentario;
     private int calificacion;

    public Comentario() {
    }

	
    public Comentario(int idcomentario, Marcador marcador, Usuario usuario, int calificacion) {
        this.idcomentario = idcomentario;
        this.marcador = marcador;
        this.usuario = usuario;
        this.calificacion = calificacion;
    }
    public Comentario(int idcomentario, Marcador marcador, Usuario usuario, String comentario, int calificacion) {
       this.idcomentario = idcomentario;
       this.marcador = marcador;
       this.usuario = usuario;
       this.comentario = comentario;
       this.calificacion = calificacion;
    }
   
    public int getIdcomentario() {
        return this.idcomentario;
    }
    
    public void setIdcomentario(int idcomentario) {
        this.idcomentario = idcomentario;
    }
    public Marcador getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(Marcador marcador) {
        this.marcador = marcador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public int getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }
}