package modelo;
// Generated 21/05/2019 04:22:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private String nombre;
     private String correo;
     private Set marcadors = new HashSet(0);

    public Tema() {
    }

	
    public Tema(String nombre, String correo) {
        this.nombre = nombre;
        this.correo = correo;
    }
    public Tema(String nombre, String correo, Set marcadors) {
       this.nombre = nombre;
       this.correo = correo;
       this.marcadors = marcadors;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }
    
    @Override
    public String toString(){
        return nombre;
    }
}


